Entity/Page.php
<?php

namespace Theodo\RogerCmsBundle\Entity;

use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Theodo\RogerCmsBundle\Repository\PageRepository;
use Theodo\RogerCmsBundle\Validator\Constraints\ExistingLayout;
use Theodo\RogerCmsBundle\Validator\TwigSyntax;

/**
 * Theodo\RogerCmsBundle\Entity\Page
 */
class Page
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var string $name
     */
    private $name;

    /**
     * @var text $content
     */
    private $content;

    /**
     * @var string $slug
     */
    private $slug;

    /**
     * @var string $breadcrumb
     */
    private $breadcrumb;

    /**
     * @var string $description
     */
    private $description;

    /**
     * @var string $status
     */
    private $status;

    /**
     * @var integer $parentId
     */
    private $parentId;

    /**
     * @var integer $layoutId
     */
    private $layoutId;

    /**
     * @var Theodo\RogerCmsBundle\Entity\Page
     */
    private $children;

    /**
     * @var Theodo\RogerCmsBundle\Entity\Page
     */
    private $parent;

    /**
     * @var string $title
     */
    private $title;

    /**
     * @var text $keywords
     */
    private $keywords;

    /**
     * @var \DateTime $publishedAt
     */
    private $publishedAt;

    /**
     * @var \DateTime $createdAt
     */
    private $createdAt;

    /**
     * @var \DateTime $updatedAt
     */
    private $updatedAt;

    /**
     * @var boolean $public
     */
    private $public;

    /**
     * @var integer $lifetime
     */
    private $lifetime;

    /**
     * @var boolean $cacheable
     */
    private $cacheable;

    /**
     * @var string $contentType
     */
    private $contentType;

    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        $this->status = PageRepository::STATUS_DRAFT;
        $this->createdAt = new \DateTime();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string $name
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set content
     *
     * @param text $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * Get content
     *
     * @return text $content
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set slug
     *
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * Get slug
     *
     * @return string $slug
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set breadcrumb
     *
     * @param string $breadcrumb
     */
    public function setBreadcrumb($breadcrumb)
    {
        $this->breadcrumb = $breadcrumb;
    }

    /**
     * Get breadcrumb
     *
     * @return string $breadcrumb
     */
    public function getBreadcrumb()
    {
        return $this->breadcrumb;
    }

    /**
     * Set description
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return string $description
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set status
     *
     * @param string $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * Get status
     *
     * @return string $status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set parentId
     *
     * @param integer $parentId
     */
    public function setParentId($parentId)
    {
        $this->parentId = $parentId;
    }

    /**
     * Get parentId
     *
     * @return integer $parentId
     */
    public function getParentId()
    {
        return $this->parentId;
    }

    /**
     * Set layoutId
     *
     * @param integer $layoutId
     */
    public function setLayoutId($layoutId)
    {
        $this->layoutId = $layoutId;
    }

    /**
     * Get layoutId
     *
     * @return integer $layoutId
     */
    public function getLayoutId()
    {
        return $this->layoutId;
    }

    /**
     * Add children
     *
     * @param Theodo\RogerCmsBundle\Entity\Page $children
     */
    public function addChildren(\Theodo\RogerCmsBundle\Entity\Page $children)
    {
        $this->children[] = $children;
    }

    /**
     * Get children
     *
     * @return Doctrine\Common\Collections\Collection $children
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Set parent
     *
     * @param Theodo\RogerCmsBundle\Entity\Page $parent
     */
    public function setParent(\Theodo\RogerCmsBundle\Entity\Page $parent)
    {
        $this->parent = $parent;
    }

    /**
     * Get parent
     *
     * @return Theodo\RogerCmsBundle\Entity\Page $parent
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Set publishedAt
     *
     * @param \DateTime $publishedAt
     */
    public function setPublishedAt($publishedAt)
    {
        $this->publishedAt = $publishedAt;
    }

    /**
     * Get publishedAt
     *
     * @return \DateTime $publishedAt
     */
    public function getPublishedAt()
    {
        return $this->publishedAt;
    }

    /**
     * Returns recursive slug
     *
     * @author Mathieu Dähne <mathieud@theodo.fr>
     * @since 2011-06-29
     *
     * @return String
     */
    public function getFullSlug()
    {
        $parent = $this->getParent();
        if ($parent && !$this->isHomepage()) {
            return $parent->getFullSlug().'/'.$this->getSlug();
        } else {
            return $this->getSlug();
        }
    }

    /**
     * Page validator
     *
     * @param ClassMetadata $metadata
     *
     * @author Vincent Guillon <vincentg@theodo.fr>
     * @since 2011-06-22
     */
    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        // Name validator: not null
        $metadata->addPropertyConstraint('name', new NotBlank());

        // Slug validator: not null and unique
        $metadata->addPropertyConstraint('slug', new NotBlank());
        $metadata->addConstraint(new UniqueEntity(array('fields' => array('slug'))));

        // Content validator: not null
        $metadata->addPropertyConstraint('content', new ExistingLayout());
        $metadata->addPropertyConstraint('content', new NotBlank());
        $metadata->addPropertyConstraint('content', new TwigSyntax());

        // Status validator: not null and available
        $metadata->addPropertyConstraint('status', new NotBlank());
        $metadata->addPropertyConstraint('status', new Choice(array(
            'choices' => PageRepository::getAvailableStatus())
        ));

    }

    /**
     * Set createdAt
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return datetime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Get updatedAt
     *
     * @return datetime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set contentType
     *
     * @param string $contentType
     */
    public function setContentType($contentType)
    {
        $this->contentType = $contentType;
    }

    /**
     * Get contentType
     *
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * Set cacheable
     *
     * @param boolean $cacheable
     */
    public function setCacheable($cacheable)
    {
        $this->cacheable = $cacheable;
    }

    /**
     * Get cacheable
     *
     * @return boolean
     */
    public function getCacheable()
    {
        return $this->cacheable;
    }

    /**
     * Set lifetime
     *
     * @param integer $lifetime
     */
    public function setLifetime($lifetime)
    {
        $this->lifetime = $lifetime;
    }

    /**
     * Get lifetime
     *
     * @return integer
     */
    public function getLifetime()
    {
        return $this->lifetime;
    }

    /**
     * Set public
     *
     * @param boolean $public
     */
    public function setPublic($public)
    {
        $this->public = $public;
    }

    /**
     * Get public
     *
     * @return boolean
     */
    public function getPublic()
    {
        return $this->public;
    }

    /**
     * Retrieve the subtype part of the Content-type declaration
     *
     * @return string
     * @author cyrillej
     * @since 2011-07-05
     */
    public function getContentSubtype()
    {
        $subtypes = PageRepository::getAvailableContentSubtypes();

        return $subtypes[$this->contentType];
    }

    /**
     * Test if the page is a homepage
     *
     * @return Boolean
     *
     * @author Fabrice Bernhard <fabriceb@theodo.fr>
     * @since 2011-08-19
     */
    public function isHomepage()
    {
        return $this->getSlug() == PageRepository::SLUG_HOMEPAGE;
    }

    /**
     * Set title
     *

Resources/views/Page/base_edit.html.twig
{% extends roger_admin_layout %}

{% set body_class = 'reversed' %}
{% set tab = 'content' %}
{% set nav = 'pages' %}

{% block javascripts_assets %}
    <script type="text/javascript"> textarea_id = 'page_content'; form_id = 'new_page'; </script>
    <script src="{{ asset('bundles/theodorogercms/js/page.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bundles/theodorogercms/js/edit_area/edit_area_full.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bundles/theodorogercms/js/twig-highlight.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bundles/theodorogercms/js/jqModal.js') }}" type="text/javascript"></script>
{% endblock %}

{% block page_title "Pages" %}

{% form_theme form 'TheodoRogerCmsBundle:Form:form_custom_layout.html.twig' %}

{% block cmscontent %}
    {% if page.id is not null %}
    <h1>{% trans %}Edit Page{% endtrans %}</h1>
    <form id="new_page" action="{{ url('page_update', { 'id': page.id }) }}" method="post" {{ form_enctype(form) }}>
    {% elseif parent_page == 'homepage' %}
    <h1>{% trans %}New Homepage{% endtrans %}</h1>
    <form id="new_page" action="{{ url('page_new', { 'parent_id': 'homepage' }) }}" method="post" {{ form_enctype(form) }}>
    {% else %}
    <h1>{% trans %}New Page{% endtrans %}</h1>
    <form id="new_page" action="{{ url('page_new', { 'parent_id': parent_page.id }) }}" method="post" {{ form_enctype(form) }}>
    {% endif %}
        <div class="title">
            {{ form_row(form.name) }}
            {{ form_row(form.title) }}
        </div>
        <div class="drawer">
            <div class="toggle_wrapper">
                <div id="extra-fields" class="drawer_contents {% if (hasErrors is defined) and hasErrors %}display{% else %}hide{% endif %}">
                    <table class="fieldset">
                        <tbody>
                            <tr>
                                <th class="label">
                                    {{ form_label(form.slug) }}
                                </th>
                                <td class="field">
                                    {{ form_widget(form.slug) }}
                                    {{ form_errors(form.slug) }}
                                </td>
                            </tr>

                            <tr>
                                <th class="label">
                                    {{ form_label(form.breadcrumb) }}
                                </th>
                                <td class="field">
                                    {{ form_widget(form.breadcrumb) }}
                                    {{ form_errors(form.breadcrumb) }}
                                </td>
                            </tr>

                            <tr>
                                <th class="label">
                                    {{ form_label(form.description) }}
                                </th>
                                <td class="field">
                                    {{ form_widget(form.description) }}
                                    {{ form_errors(form.description) }}
                                </td>
                            </tr>

                            <tr>
                                <th class="label">
                                    {{ form_label(form.keywords) }}
                                </th>
                                <td class="field">
                                    {{ form_widget(form.keywords) }}
                                    {{ form_errors(form.keywords) }}
                                </td>
                            </tr>

                            <tr>
                                <th class="label">
                                    {{ form_label(form.content_type) }}
                                </th>
                                <td class="field">
                                    {{ form_widget(form.content_type) }}
                                    {{ form_errors(form.content_type) }}
                                </td>
                            </tr>

                            <tr>
                                <th class="label">
                                    {% trans %}Cache{% endtrans %}
                                </th>
                                <td class="field">
                                    <p>
                                        {{ form_label(form.cacheable, 'Static Content?') }}
                                        {{ form_widget(form.cacheable) }}
                                        {{ form_errors(form.cacheable) }}
                                        <em>{% trans %}Returns a 304 "not modified" status, when the template has not changed since last visit.{% endtrans %}</em>
                                    </p>
                                    <p>
                                        {{ form_label(form.public, 'Visitor-independant content?') }}
                                        {{ form_widget(form.public) }}
                                        {{ form_errors(form.public) }}
                                        <em>{% trans %}Allows proxies to cache the same content for different visitors.{% endtrans %}</em>
                                    </p>
                                    <p>
                                        {{ form_label(form.lifetime, 'Cache lifetime:') }}
                                        {{ form_widget(form.lifetime, { 'attr': {'style': 'width: 100px;'} }) }}
                                        <em>{% trans %}Does a full content caching, except for snippets, during the specified lifetime. Leave empty for no cache.{% endtrans %}</em>
                                        {{ form_errors(form.lifetime) }}
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="drawer_handle">
                <a id="link-more-fields" class="toggle more extra-fields-link {% if (hasErrors is not defined) or not hasErrors %}display-ib{% else %}hide{% endif %}" href="#">
                  {% trans %}More{% endtrans %}
                </a>
                <a id="link-less-fields" class="toggle less extra-fields-link {% if (hasErrors is defined) and hasErrors %}display-ib{% else %}hide{% endif %}" href="#">
                  {% trans %}Less{% endtrans %}
                </a>
            </div>
        </div>
        <div id="tab_control">
            <div class="tabs" id="tabs">

                <div id="tab_toolbar">
                    <a class="popup" href="#add_part_popup" title="{% trans %}Add Part{% endtrans %}">
                        <img alt="{% trans %}Add Part{% endtrans %}" src="{{ asset('bundles/theodorogercms/images/admin/add_tab.png') }}" />
                    </a>
                </div>
                {% for tab_name in tabs|keys %}
                    <a id="tab_{{ tab_name }}" href="#" class="tab {{ loop.first ? 'here' : '' }} ">
                      <span> {{ tab_name }} </span>
                      <img src="{{ asset('bundles/theodorogercms/images/admin/tab_close.png') }}" class="close" alt="{% trans %}Remove part{% endtrans %}" title="{% trans %}Remove part{% endtrans %}" />
                    </a>
                {% endfor%}
            </div>
            <div class="pages" id="pages">
                {% for tab_name, tab_content in tabs %}
                    <div class="page {{ loop.first ? '' : 'hide' }}" id="page_{{ tab_name }}">
                        <div class="part" id="part_{{ tab_name }}">
                            <p>
                                {{ form_errors(form.content) }}

                                <span class="reference_links">
                                    <a href="http://www.twig-project.org/documentation" target="_blank">{% trans %}Twig documentation{% endtrans %}</a>
                                </span>
                            </p>
                            <div>
                                <textarea id="page_content_{{ tab_name }}" class="textarea large" name="page_block[{{ tab_name }}]" style="width: 100%;">{{ tab_content }}</textarea>
                            </div>
                        </div>
                    </div>
                {% endfor%}
            </div>
        </div>
        <div class="set">
             <p
                <label class="required" for="page_layout">Layout</label>
                <select class="required" name="page_layout" id="page_layout">
                    <option value=""></option>
                    {% for layout in layouts %}
                        <option {{ layout_name == layout.name ? 'selected="selected"' : '' }} value="{{layout.name}}">{{layout.name}}</option>
                    {% endfor%}
                </select>
            </p>
        </div>
        <div class="set">
            <p>
                {{ form_row(form.status) }}
            </p>
            {% if page.id is not null %}
                <div>
                    {{ form_label(form.published_at) }}
                    {{ form_widget(form.published_at) }}
                    {{ form_errors(form.published_at) }}
                </div>
            {% endif %}
        </div>

        {{ form_widget(form._token) }}
        {{ form_widget(form.parent_id) }}
        <p class="buttons" style="clear: left;">
            <input accesskey="S" class="button" type="submit" value="{% trans %}Save Changes{% endtrans %}" name="save-and-list" />
            <input accesskey="s" class="button" type="submit" value="{% trans %}Save and Continue Editing{% endtrans %}" name="save-and-edit" />
            {% trans %}or{% endtrans %}
            <a href="{{ url('page_list') }}">{% trans %}Cancel{% endtrans %}</a>
        </p>
        {# <p class="updated_line">
          {% trans %}Last Updated by <strong>Administrator</strong> at 07:27 am on January 02, 2009{% endtrans %}
        </p> #}
    </form>

    <div id="popin-delete" class="jqmWindow">
        <div class="modal-title">
          <a href="#" class="jqmClose" title="Close window">X</a>
          <h4>Delete block</h4>
        </div>
        <div class="modal-content">
          <p>Delete this block ?</p>
          <input type="submit" value="yes" name="yes">
          <input type="submit" value="no" name="no">
        </div>
    </div>

    <div id="popin-add" class="jqmWindow">
        <div class="modal-title">
          <a href="#" class="jqmClose" title="Close window">X</a>
          <h4>Create new block</h4>
        </div>
        <div class="modal-content">
          <p>Add new block</p>
          <input type="text" value="" name="new-block">
          <input type="submit" value="ok" name="ok">
        </div>
    </div>
{% endblock %}

Resources/views/Page/base_index.html.twig
{% extends roger_admin_layout %}

{% block javascripts_assets %}
<script src="{{ asset('bundles/theodorogercms/js/page.js') }}" type="text/javascript"></script>
{% endblock %}

{% set tab = 'content' %}
{% set nav = 'pages' %}

{% block page_title "Pages" %}

{% block cmscontent %}
{% if pages|length == 0 %}
    <div id="actions">
        <ul>
            <li>
              <a href="{{ url('page_new', {'parent_id' : 'homepage'}) }}">
                  <img src="{{ asset('bundles/theodorogercms/images/admin/plus.png') }}" alt="">
                  {% trans %}New Homepage{% endtrans %}
              </a>
            </li>
        </ul>
    </div>
{% endif %}
<div class="outset">
    <table class="index" id="site_map" summary="{% trans %}Page hierarchy of the current site{% endtrans %}">
        <thead>
            <tr>
                <th class="page">{% trans %}Page{% endtrans %}</th>
                <th class="status">{% trans %}Status{% endtrans %}</th>
                <th class="modify" colspan="2">{% trans %}Modify{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
          {% if pages|length == 0 %}
            <td colspan="4" class="empty">{% trans %}No pages{% endtrans %}</td>
          {% else %}
            {% include "TheodoRogerCmsBundle:Page:page-list.html.twig" with {'pages': pages, 'level' : 0} %}
          {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

Resources/views/Page/base_remove.html.twig
{% extends roger_admin_layout %}

{% set tab = 'content' %}
{% set nav = 'pages' %}

{% block page_title "Remove Pages" %}

{% block cmscontent %}
<h1>{% trans %}Remove{% endtrans %} {{page.name}}</h1>
<p>{% trans %}Are you sure you want to <strong class="warning">permanently remove</strong> the following pages?{% endtrans %}</p>

<div class="inset">
    {% render "TheodoRogerCmsBundle:Backend\\Page:siteMapComponent" with {'from_id': page.id} %}
</div>

<form class="edit_page" action="{{ url('page_remove', {'id' : page.id}) }}" method="post">
    <p class="buttons">
        <input class="button" type="submit" value="{% trans %}Delete{% endtrans %}" />
        {% trans %}or{% endtrans %}
        <a href="{{ url('page_list') }}">{% trans %}Cancel{% endtrans %}</a>
    </p>
</form>
{% endblock %}

Resources/views/Page/index.html.twig
{% extends "TheodoRogerCmsBundle::layout.html.twig" %}

{% block javascripts_assets %}
<script src="{{ asset('bundles/theodorogercms/js/page.js') }}" type="text/javascript"></script>
{% endblock %}

{% set tab = 'content' %}
{% set nav = 'pages' %}

{% block page_title "Pages" %}

{% block cmscontent %}
{% if pages|length == 0 %}
    <div id="actions">
        <ul>
            <li>
              <a href="{{ url('roger_cms_page_new', {'parentId' : 'homepage'}) }}">
                  <img src="{{ asset('bundles/theodorogercms/images/admin/plus.png') }}" alt="">
                  {% trans %}New Homepage{% endtrans %}
              </a>
            </li>
        </ul>
    </div>
{% endif %}
<div class="outset">
    <table class="index" id="site_map" summary="{% trans %}Page hierarchy of the current site{% endtrans %}">
        <thead>
            <tr>
                <th class="page">{% trans %}Page{% endtrans %}</th>
                <th class="status">{% trans %}Status{% endtrans %}</th>
                <th class="modify" colspan="2">{% trans %}Modify{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
          {% if pages|length == 0 %}
            <td colspan="4" class="empty">{% trans %}No pages{% endtrans %}</td>
          {% else %}
            {% include "TheodoRogerCmsBundle:Page:page-list.html.twig" with {'pages': pages, 'level' : 0} %}
          {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

Resources/views/Page/page-list.html.twig
{% for page in pages %}
    {% include "TheodoRogerCmsBundle:Page:page-row.html.twig" with {'page': page, 'level': level} %}
{% endfor %}

Resources/views/Page/page-row.html.twig
{% set padding_left %}
    {% if level == 0 %}
        9px
    {% elseif level == 1 %}
        32px
    {% else %}
        {{ level * 27 }}px
    {% endif %}
{% endset %}

<tr
  id="page_{{ page.id }}"
  class="
  node page level_{{ level }}
  {% if page.parent %} child_page_{{ page.parentId }}{% endif %}
  ">
    <td class="page" style="padding-left: {% spaceless %}{{ padding_left }}{% endspaceless %};">
        <span class="w1">
            {% if page.children|length > 0 and page.parent %}
                <a class="expandable" href="{{ url('roger_cms_page_expand', {'id' : page.id, 'level' : level + 1}) }}">
                    <img alt="toggle children" class="expander" src="{{ asset('bundles/theodorogercms/images/admin/expand.png') }}" />
                </a>
            {% endif %}
            <a id="edit-{{ page.slug }}" href="{{ url('roger_cms_page_edit', {'id' : page.id}) }}">
                <span class="content_type">{{ page.contentSubtype }}</span>
                <img alt="" class="icon" src="{{ asset('bundles/theodorogercms/images/admin/roger_page.png') }}" />
                <span class="title">{{ page.name }}</span>
            </a>
            <img src="{{ asset('bundles/theodorogercms/images/admin/spinner.gif') }}" class="ajax-loader hide busy" alt="" />
        </span>
    </td>
    <td class="status">
        {{ page.status|trans }}
    </td>
    <td class="add_child">
        <a id="new-{{ page.slug }}-child" href="{{ url('roger_cms_page_new', {'parentId' : page.id}) }}">
          {% trans %}Add Child{% endtrans %}
        </a>
    </td>
    <td class="remove">
        <a id="remove-{{ page.slug }}" href="{{ url('roger_cms_page_remove', {'id' : page.id}) }}">
          {% trans %}Remove{% endtrans %}
        </a>
    </td>
</tr>

{% if page.children|length > 0 and not page.parent %}
  {% for child in page.children %}
    {% include "TheodoRogerCmsBundle:Page:page-row.html.twig" with {'page': child, 'level': level + 1} %}
  {% endfor %}
{% endif %}

Resources/views/Page/remove.html.twig
{% extends "TheodoRogerCmsBundle::layout.html.twig" %}

{% set tab = 'content' %}
{% set nav = 'pages' %}

{% block page_title "Remove Pages" %}

{% block cmscontent %}
<h1>{% trans %}Remove{% endtrans %} {{page.name}}</h1>
<p>{% trans %}Are you sure you want to <strong class="warning">permanently remove</strong> the following pages?{% endtrans %}</p>

<div class="inset">
    {% render "TheodoRogerCmsBundle:Backend\\Page:siteMapComponent" with {'fromId': page.id} %}
</div>

<form class="edit_page" action="{{ url('roger_cms_page_remove', {'id' : page.id}) }}" method="post">
    <p class="buttons">
        <input class="button" type="submit" value="{% trans %}Delete{% endtrans %}" />
        {% trans %}or{% endtrans %}
        <a href="{{ url('roger_cms_page_list') }}">{% trans %}Cancel{% endtrans %}</a>
    </p>
</form>
{% endblock %}

Resources/views/Page/site-map-component.html.twig
<table id="site_map" class="index">
  <tbody>
    {% include "TheodoRogerCmsBundle:Page:site-map-row.html.twig" with {'page': page, 'level': level} %}
  </tbody>
</table>

Resources/views/Page/site-map-row.html.twig
{% set padding_left %}
    {% if level == 0 %}
        9px
    {% elseif level == 1 %}
        32px
    {% else %}
        {{ level * 27 }}px
    {% endif %}
{% endset %}

<tr id="page_{{ page.id }}" class="level_{{ level }} no_children node page">
    <td style="padding-left: {% spaceless %}{{ padding_left }}{% endspaceless %};" class="page">
        <span class="w1"><img alt="" class="icon" src="{{ asset('bundles/theodorogercms/images/admin/roger_page.png') }}" />{{ page.name }}</span>
    </td>
</tr>

{% for child in page.children %}
    {% include "TheodoRogerCmsBundle:Page:site-map-row.html.twig" with {'page': child, 'level': level + 1} %}
{% endfor %}

Resources/views/Page/visible.html.twig
{% autoescape false %}
    {{ content }}
{% endautoescape %}